const API = window.ODISHA_RASOI_API || '/api';
let cart = [];

function changeQuantity(button, amount) { const box = button.parentElement, number = box.querySelector('span'); number.innerText = Math.max(1, parseInt(number.innerText) + amount); }
function addToCart(itemName, price, button) { const quantity = parseInt(button.parentElement.querySelector('.qty span').innerText); const existing = cart.find(i => i.name === itemName); if (existing) existing.quantity += quantity; else cart.push({ name: itemName, price: Number(price), quantity }); button.parentElement.querySelector('.qty span').innerText = '1'; button.innerText = 'Added ✓'; setTimeout(() => button.innerText = 'Add to Cart', 1000); updateCart(); }
function updateCart() { const items = document.getElementById('cart-items'), count = document.getElementById('cart-count'), total = document.getElementById('cart-total'); if (!items) return; items.innerHTML = ''; let n = 0, t = 0; if (!cart.length) items.innerHTML = '<div class="empty-cart"><span>🛒</span><p>Your cart is empty</p><small>Add some delicious Odia dishes!</small></div>'; cart.forEach((item, index) => { const sum = item.price * item.quantity; n += item.quantity; t += sum; items.innerHTML += `<div class="cart-item"><div class="cart-item-info"><h3>${esc(item.name)}</h3><p>₹${item.price} × ${item.quantity}</p></div><div class="cart-item-right"><strong>₹${sum}</strong><div class="cart-item-controls"><button onclick="changeCartQuantity(${index},-1)">−</button><span>${item.quantity}</span><button onclick="changeCartQuantity(${index},1)">+</button><button class="remove-cart" onclick="removeFromCart(${index})">×</button></div></div></div>` }); if (count) count.innerText = n; if (total) total.innerText = t; }
function changeCartQuantity(index, amount) { cart[index].quantity += amount; if (cart[index].quantity <= 0) cart.splice(index, 1); updateCart(); }
function removeFromCart(index) { cart.splice(index, 1); updateCart(); }
function clearCart() { cart = []; updateCart(); }
function checkoutCart() { if (!cart.length) { alert('Your cart is empty. Please add some food first.'); return; } document.getElementById('checkout-modal')?.classList.remove('hidden'); }
function closeCheckout() { document.getElementById('checkout-modal')?.classList.add('hidden'); }
async function submitOrder(event) { event.preventDefault(); if (!cart.length) return; const form = event.target, button = form.querySelector('button[type="submit"]'); button.disabled = true; button.innerText = 'Placing Order...'; try { const r = await fetch(`${API}/orders`, { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({ name: document.getElementById('order-name').value.trim(), phone: document.getElementById('order-phone').value.trim(), items: cart.map(i => ({ name: i.name, price: i.price, quantity: i.quantity })) }) }); const d = await r.json(); if (!r.ok) throw Error(d.message || 'Could not place order'); closeCheckout(); document.getElementById('order-success-id').innerText = '#' + d.id; document.getElementById('order-success').classList.remove('hidden'); cart = []; updateCart(); form.reset(); } catch (e) { alert(e.message || 'Could not place your order. Please try again.'); } finally { button.disabled = false; button.innerText = 'Place Order'; } }
function filterMenu(category, button) { document.querySelectorAll('.food-card').forEach(card => card.classList.toggle('hidden', category !== 'all' && card.dataset.category !== category)); document.querySelectorAll('.filter-btn').forEach(b => b.classList.remove('active')); button.classList.add('active'); }
function filterGallery(category, button) { document.querySelectorAll('.gallery-item').forEach(item => item.classList.toggle('gallery-hidden', category !== 'all' && item.dataset.gallery !== category)); document.querySelectorAll('.gallery-filter-btn').forEach(b => b.classList.remove('active')); button.classList.add('active'); }
function openLightbox(src) { const l = document.getElementById('lightbox'); if (l) { document.getElementById('lightbox-image').src = src; l.classList.add('show'); } }
function closeLightbox() { document.getElementById('lightbox')?.classList.remove('show'); }
async function submitContactForm(event) { event.preventDefault(); const form = event.target, success = document.getElementById('contact-success'), button = form.querySelector('button[type="submit"]'); button.disabled = true; button.innerText = 'Sending...'; try { const r = await fetch(`${API}/feedback`, { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({ name: document.getElementById('contact-name').value.trim(), email: document.getElementById('contact-email').value.trim(), phone: document.getElementById('contact-phone').value.trim(), message: document.getElementById('contact-message').value.trim() }) }); const d = await r.json(); if (!r.ok) throw Error(d.message || 'Unable to send your message'); success.innerText = d.message || 'Thank you! Your message has been received. We will get back to you soon.'; success.classList.add('show'); form.reset(); } catch (e) { alert(e.message || 'Unable to send your message. Please try again.'); } finally { button.disabled = false; button.innerText = 'Send Message'; } }
async function submitReservation(event) { event.preventDefault(); const form = event.target, button = form.querySelector('button[type="submit"]'), success = document.getElementById('reservation-success'); button.disabled = true; button.innerText = 'Booking...'; try { const payload = Object.fromEntries(new FormData(form).entries()); const r = await fetch(`${API}/reservations`, { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify(payload) }); const d = await r.json(); if (!r.ok) throw Error(d.message || 'Unable to submit reservation'); success.innerText = d.message || 'Your reservation request has been submitted! We will contact you to confirm your table.'; success.classList.add('show'); form.reset(); } catch (e) { alert(e.message || 'Unable to submit your reservation. Please try again.'); } finally { button.disabled = false; button.innerText = 'Reserve Table'; } }
document.addEventListener('keydown', e => { if (e.key === 'Escape') { closeLightbox(); closeCheckout(); } });
function esc(v) { return String(v ?? '').replace(/[&<>'"]/g, c => ({ '&': '&amp;', '<': '&lt;', '>': '&gt;', "'": '&#39;', '"': '&quot;' }[c])); }
const menuToggle = document.getElementById('menu-toggle'), navMenu = document.getElementById('nav-menu'); if (menuToggle && navMenu) menuToggle.addEventListener('click', () => navMenu.classList.toggle('show'));
