const API='http://localhost:5000/api';
const token=()=>localStorage.getItem('odishaAdminToken');
const headers=()=>({Authorization:`Bearer ${token()}`});
if(document.getElementById('login-form')){if(token())location.href='dashboard.html';document.getElementById('login-form').addEventListener('submit',async e=>{e.preventDefault();const error=document.getElementById('login-error');error.textContent='';try{const r=await fetch(`${API}/admin/login`,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({email:email.value.trim(),password:password.value})});const d=await r.json();if(!r.ok)throw Error(d.message);localStorage.setItem('odishaAdminToken',d.token);location.href='dashboard.html';}catch(x){error.textContent=x.message||'Login failed';}});}
if(document.getElementById('dashboard')){if(!token())location.href='login.html';loadAll();}
async function api(path,options={}){const r=await fetch(API+path,{...options,headers:{...headers(),...(options.headers||{})}});if(r.status===401){logout();return;}const d=await r.json();if(!r.ok)throw Error(d.message||'Request failed');return d;}
async function loadAll(){try{const [stats,menu,orders,customers,hours,feedback]=await Promise.all([api('/dashboard'),api('/menu'),api('/orders'),api('/customers'),api('/hours'),api('/feedback')]);renderStats(stats);renderMenu(menu);renderOrders(orders);renderCustomers(customers);renderFeedback(feedback);renderHours(hours);}catch(e){console.error(e);}}
function renderStats(s){document.getElementById('daily-orders').textContent=s.dailyOrders;document.getElementById('daily-revenue').textContent='₹'+Number(s.dailyRevenue).toFixed(0);document.getElementById('menu-count').textContent=s.menuItems;document.getElementById('customer-count').textContent=s.customers;}
function imageUrl(url){return url?(url.startsWith('http')?url:`${API.replace('/api','')}${url}`):'';}
function renderMenu(items){document.getElementById('menu-body').innerHTML=items.map(i=>`<tr><td>${i.image_url?`<img src="${esc(imageUrl(i.image_url))}" alt="${esc(i.name)}" class="menu-thumb">`:'<span class="no-image">No image</span>'}</td><td><strong>${esc(i.name)}</strong></td><td>${esc(i.category)}</td><td>₹${Number(i.price).toFixed(0)}</td><td><span class="status ${i.available?'':'off'}">${i.available?'Available':'Unavailable'}</span></td><td class="actions"><button class="secondary" onclick='openEditModal(${JSON.stringify(i)})'>Edit</button><button class="secondary" onclick="toggleAvailability(${i.id},${!i.available})">${i.available?'Disable':'Enable'}</button><button class="danger" onclick="deleteItem(${i.id})">Delete</button></td></tr>`).join('')||'<tr><td colspan="6">No menu items.</td></tr>';}
function renderOrders(items){document.getElementById('orders-body').innerHTML=items.map(o=>`<tr><td>#${o.id}</td><td>${esc(o.name)}</td><td>${esc(o.phone)}</td><td>${o.items.map(i=>esc(i.name)+' × '+i.quantity).join(', ')}</td><td>₹${Number(o.total).toFixed(0)}</td><td><select onchange="updateOrderStatus(${o.id},this.value)">${['Pending','Confirmed','Preparing','Ready','Completed','Cancelled'].map(s=>`<option ${s===o.status?'selected':''}>${s}</option>`).join('')}</select></td><td>${new Date(o.created_at).toLocaleString()}</td></tr>`).join('')||'<tr><td colspan="7">No orders yet.</td></tr>';}
async function updateOrderStatus(id,status){try{await api('/orders/'+id+'/status',{method:'PUT',headers:{'Content-Type':'application/json'},body:JSON.stringify({status})});}catch(e){alert(e.message);loadAll();}}
function renderCustomers(items){document.getElementById('customers-body').innerHTML=items.map(c=>`<tr><td>${esc(c.name)}</td><td>${esc(c.phone)}</td><td>${c.orders}</td><td>₹${Number(c.total_spent).toFixed(0)}</td></tr>`).join('')||'<tr><td colspan="4">No customers yet.</td></tr>';}
function renderFeedback(items){document.getElementById('feedback-body').innerHTML=items.map(f=>`<tr><td>${esc(f.name)}</td><td>${esc(f.email)}</td><td>${esc(f.phone)}</td><td>${esc(f.message)}</td><td>${new Date(f.created_at).toLocaleString()}</td></tr>`).join('')||'<tr><td colspan="5">No feedback yet.</td></tr>';}
function renderHours(items){document.getElementById('hours-list').innerHTML=items.map(h=>`<div class="hour-row"><strong>${esc(h.day_name)}</strong><label><input type="checkbox" id="closed-${h.id}" ${h.is_closed?'checked':''} onchange="saveHours(${h.id})"> Closed</label><input type="time" id="open-${h.id}" value="${h.open_time||''}" ${h.is_closed?'disabled':''}><span>to</span><input type="time" id="close-${h.id}" value="${h.close_time||''}" ${h.is_closed?'disabled':''}><button class="secondary" onclick="saveHours(${h.id})">Save</button></div>`).join('');}
async function saveHours(id){const closed=document.getElementById('closed-'+id).checked;await api('/hours/'+id,{method:'PUT',headers:{'Content-Type':'application/json'},body:JSON.stringify({is_closed:closed,open_time:document.getElementById('open-'+id).value,close_time:document.getElementById('close-'+id).value})});loadAll();}
function resetImagePreview(){const p=document.getElementById('image-preview'),img=document.getElementById('food-image-preview');p.classList.add('hidden');img.removeAttribute('src');}
function previewDishImage(e){const file=e.target.files[0];if(!file){resetImagePreview();return;}if(file.size>5*1024*1024){alert('Image must be 5 MB or smaller.');e.target.value='';resetImagePreview();return;}const reader=new FileReader();reader.onload=()=>{document.getElementById('food-image-preview').src=reader.result;document.getElementById('image-preview').classList.remove('hidden');};reader.readAsDataURL(file);}
function openAddModal(){document.getElementById('modal-title').textContent='Add Food';document.getElementById('food-form').reset();document.getElementById('food-id').value='';document.getElementById('food-available').checked=true;resetImagePreview();document.getElementById('food-modal').classList.remove('hidden');}
function openEditModal(i){document.getElementById('modal-title').textContent='Edit Food';document.getElementById('food-id').value=i.id;document.getElementById('food-name').value=i.name;document.getElementById('food-category').value=i.category;document.getElementById('food-price').value=i.price;document.getElementById('food-description').value=i.description||'';document.getElementById('food-available').checked=i.available;document.getElementById('food-image').value='';if(i.image_url){document.getElementById('food-image-preview').src=imageUrl(i.image_url);document.getElementById('image-preview').classList.remove('hidden');}else resetImagePreview();document.getElementById('food-modal').classList.remove('hidden');}
function closeModal(){document.getElementById('food-modal').classList.add('hidden');}
document.getElementById('food-form')?.addEventListener('submit',async e=>{e.preventDefault();const submit=e.target.querySelector('button[type="submit"]');submit.disabled=true;try{const fd=new FormData();fd.append('name',document.getElementById('food-name').value.trim());fd.append('category',document.getElementById('food-category').value);fd.append('price',document.getElementById('food-price').value);fd.append('description',document.getElementById('food-description').value);fd.append('available',document.getElementById('food-available').checked);if(document.getElementById('food-image').files[0])fd.append('image',document.getElementById('food-image').files[0]);const id=document.getElementById('food-id').value;await api(id?'/menu/'+id:'/menu',{method:id?'PUT':'POST',body:fd});closeModal();loadAll();}catch(x){alert(x.message||'Could not save food.');}finally{submit.disabled=false;}});
async function toggleAvailability(id,available){await api('/menu/'+id,{method:'PUT',headers:{'Content-Type':'application/json'},body:JSON.stringify({available})});loadAll();}
async function deleteItem(id){if(confirm('Delete this food item?')){await api('/menu/'+id,{method:'DELETE'});loadAll();}}
function logout(){localStorage.removeItem('odishaAdminToken');location.href='login.html';}
function esc(v){return String(v??'').replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]));}
